MPESA_CONSUMER_KEY: '2jHLG0U8uezHWOJTDaQd3U3KIFxSaQ5T'
MPESA_CONSUMER_SECRET: 'HhVfmPEt3Mj6OZxL'
MPESA_PASSKEY: 'bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919'
MPESA_SHORTCODE: '174379'
MPESA_INITIATOR_NAME: 'testapi'
MPESA_INITIATOR_PASSWORD: 'Safaricom999!*!'
CALLBACK_URL: 'https://webhook.site/2aa27f02-5cb4-4104-aaec-b9b89b34a479'
REGISTER_URL: "https://sandbox.safaricom.co.ke/mpesa/c2b/v1/registerurl"